"""HTTP/business boundary. Concrete services must use persistent transactions."""
from dataclasses import dataclass
from typing import Any, Literal, Protocol


@dataclass(frozen=True)
class Identity:
    tenant_id: str
    principal_id: str
    role: Literal["owner", "maintainer", "viewer"]


class ServiceError(Exception):
    def __init__(self, status: int, code: str, message: str, conflict: dict | None = None):
        super().__init__(message)
        self.status, self.code, self.message, self.conflict = status, code, message, conflict


class Services(Protocol):
    # Authentication implementation/secret loading belongs to the host.
    def issue_token(self, identifier: str, credential: str) -> dict: ...
    def list_projects(self, identity: Identity) -> list[dict]: ...
    def list_requirements(self, identity: Identity, project_id: str) -> list[dict]: ...
    def list_requirement_changes(self, identity: Identity, project_id: str, requirement_id: str) -> list[dict]: ...
    def get_change_diff(self, identity: Identity, project_id: str, change_id: str) -> dict: ...
    def start_sync(self, identity: Identity, body: dict, key: str, request_id: str) -> dict: ...
    def get_sync(self, identity: Identity, job_id: str) -> dict: ...
    def create_export(self, identity: Identity, project_id: str, body: dict, key: str, request_id: str) -> dict: ...
    def get_export(self, identity: Identity, export_id: str) -> dict: ...
    def list_principals(self, identity: Identity) -> list[dict]: ...
    def list_tasks(self, identity: Identity, principal_id: str, project_id: str | None) -> list[dict]: ...
    def list_discussions(self, identity: Identity, project_id: str, target_id: str | None) -> list[dict]: ...
    def get_discussion(self, identity: Identity, discussion_id: str) -> dict: ...
    def create_discussion(self, identity: Identity, project_id: str, body: dict, key: str, request_id: str) -> dict: ...
    def update_discussion(self, identity: Identity, discussion_id: str, body: dict, key: str, request_id: str) -> dict: ...
    def delete_discussion(self, identity: Identity, discussion_id: str, body: dict, key: str, request_id: str) -> dict: ...
    def list_posts(self, identity: Identity, discussion_id: str) -> list[dict]: ...
    def get_post(self, identity: Identity, post_id: str) -> dict: ...
    def create_post(self, identity: Identity, discussion_id: str, body: dict, key: str, request_id: str) -> dict: ...
    def update_post(self, identity: Identity, post_id: str, body: dict, key: str, request_id: str) -> dict: ...
    def delete_post(self, identity: Identity, post_id: str, body: dict, key: str, request_id: str) -> dict: ...
    def list_claims(self, identity: Identity, project_id: str, state: str | None) -> list[dict]: ...
    def get_claim(self, identity: Identity, claim_id: str) -> dict: ...
    def create_claim(self, identity: Identity, project_id: str, body: dict, key: str, request_id: str) -> dict: ...
    def update_claim(self, identity: Identity, claim_id: str, body: dict, key: str, request_id: str) -> dict: ...
    def list_notifications(self, identity: Identity) -> list[dict]: ...
    def get_notification(self, identity: Identity, notification_id: str) -> dict: ...
    def update_notification(self, identity: Identity, notification_id: str, body: dict, key: str, request_id: str) -> dict: ...


# Write services must atomically enforce tenant/project scope, revision, owner
# predicates, idempotency receipt and audit. HTTP checks are defense in depth,
# not a replacement for the transaction's WHERE revision/created_by clauses.
